spring:
    application:
        name: allmusic-service
    datasource:
        url: jdbc:h2:mem:allmusicdb
        driver-class-name: org.h2.Driver
        username: allmusic
        password: ''
        #url: jdbc:postgresql://localhost:5432/allmusicdb
        #driver-class-name: org.postgresql.Driver
        #username: postgresql
        #password: 
    jpa:
        #database-platform: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
            path: /h2-console
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-123456.okta.com/oauth2/default
                    jwk-set-uri: "https://example.com/.well-known/jwks.json"
server:
  port: 8080
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        hostname: localhost
